CREATE TABLE PURCHASES(
id INT NOT NULL AUTO_INCREMENT,
product VARCHAR(100) NOT NULL,
quantity INT NOT NULL,
purchase_date DATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (product) REFERENCES PRODUCTS(name)
)